### ISSUE TITLE
Chat Room for General Comments

### ISSUE THREAD

**Issue by rhaubt** [NinaTanneberger/studio3#27]
I assume all is going well. Have not heard from you today. :)

**Comment by rhaubt** [comment]
Please make sure to fill out this form at the end of each week.
https://goo.gl/forms/fB2ADePixwIXqKRw1

**Comment by NinaTanneberger** [comment]
Hi Rob, yeah I've just been working on my style guide and a little tired. Not much to update as I'm just doing research on styles mostly.

**Comment by NinaTanneberger** [comment]
Hey Rob, with my site the client will need to access editing functions to upload information and pictures etc. I assume I would create a login for them where they can do these things but some advice on how I would go about this would be great. Does WordPress already do this when you upload the website to the host?

**Comment by rhaubt** [comment]
wordpress has basic user management build in.

In the backend navigate to User > New User and create a new user profile. You can also set the access privileges here eg Admin, Author, Editor etc. Have a read on the wordpress roles here:

https://en.support.wordpress.com/user-roles/
https://www.wpbeginner.com/beginners-guide/wordpress-user-roles-and-permissions/

If you need advanced functions have a looked at User Management plugins.

**Comment by rhaubt** [comment]
Did you manage to get Wordpress going on your machine?

**Comment by NinaTanneberger** [comment]
Yeah I got that going a while back

**Comment by NinaTanneberger** [comment]
So I've been looking at how WordPress works and I think I would like to change my workflow. I know how to do it but I want to check with you that I can do it to meet criteria with this unit. 

I'd like to setup WordPress straight onto the host and work on it online. That way I can take it anywhere I want and show my client in person via my tablet and she can also show her band remotely. I would still need to discuss this with the client though as she would have to pay me for the hosting.

I feel like this would be better for me as I do know how to code backend but I am more interested in becoming a _designer_ than a developer so I think learning interface tools and plugins would be a good advantage for me in this trimester rather than focusing on the coding aspect.

What do you think?
